name: Feature request
description: A feature or behavior you want
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What should it do?
      description: How it should work, and how you would use it.
    validations:
      required: true
