-- Generated by System Settings (Quickshell MacOS/MacSettings.qml).
-- Read by hypr/custom.lua. Edit in System Settings instead.
return {
    tap_to_click   = true,
    natural_scroll = true,
    traffic_lights = true,
}
