-- Your changes. Loads last, so anything here wins over macos/*.lua.
-- Updates never replace this file. More examples: examples/ in the repo.
--
-- A laptop panel at 1.5x:
--   hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.5 })
--
-- Replace a shortcut:
--   hl.unbind("SUPER + RETURN")
--   hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("foot"), { description = "Terminal" })
--
-- Start something at login:
--   hl.on("hyprland.start", function() hl.exec_cmd("nextcloud --background") end)
